## Data Engineering : Mathematics for Machine Learning and Data Science

*Questions* 

1. Compute the scalar products between any pair of vectors u5.uj


In [ ]:
import numpy as np 

# we want to create a loop for sclalar products between any other vector different from u5
# between u1 and u4 

U=[]
U.append(np.array([-6,-3,3,-3]))
U.append(np.array([-8,4,1,-1]))
U.append(np.array([-4,-3,4,-8]))
U.append(np.array([-8,-6,-7,-1]))



for i in range(0,len(U)): 
  for j in range(0,len(U)):
    scalar = np.vdot(U[i],U[j])
    print ('the scalar product between',U[i], 'and', U[j],'is that', scalar) 



  

the scalar product between [-6 -3  3 -3] and [-6 -3  3 -3] is that 63
the scalar product between [-6 -3  3 -3] and [-8  4  1 -1] is that 42
the scalar product between [-6 -3  3 -3] and [-4 -3  4 -8] is that 69
the scalar product between [-6 -3  3 -3] and [-8 -6 -7 -1] is that 48
the scalar product between [-8  4  1 -1] and [-6 -3  3 -3] is that 42
the scalar product between [-8  4  1 -1] and [-8  4  1 -1] is that 82
the scalar product between [-8  4  1 -1] and [-4 -3  4 -8] is that 32
the scalar product between [-8  4  1 -1] and [-8 -6 -7 -1] is that 34
the scalar product between [-4 -3  4 -8] and [-6 -3  3 -3] is that 69
the scalar product between [-4 -3  4 -8] and [-8  4  1 -1] is that 32
the scalar product between [-4 -3  4 -8] and [-4 -3  4 -8] is that 105
the scalar product between [-4 -3  4 -8] and [-8 -6 -7 -1] is that 30
the scalar product between [-8 -6 -7 -1] and [-6 -3  3 -3] is that 48
the scalar product between [-8 -6 -7 -1] and [-8  4  1 -1] is that 34
the scalar product 

2. Using the Gram-Schmidt algo, and starting from vector {u1,u2,u3,u4} construct an orthonormal family of vectors {v1,v2,v3,v4} 

![Screenshot from 2020-01-31 11-44-18.png](/home/shalom/Desktop)


In [ ]:
# here the algorithm of Gram-Schmidt method 

# the principal of this method is to construct a orthonomal base of a sub-space
# starting with a free family of elements 

# we will use the projection of the free family intruded before on orthonormal 
#vector to construct a space of orthonormal vector 

import numpy as np

def proj(u,v):
    return np.dot(u,v)/np.dot(v,v)*v



V=[]
V.append(U[0])
for n in range(1,len(U)):
    somme_proj = 0
    for i in range(n):
        somme_proj += proj(U[n],V[i])
    V.append(U[n]-somme_proj)

e=[]
for n in range(len(V)):
    e.append(V[n]/np.linalg.norm(V[n]))
e

print("the new orthogonal family is", e)


the new orthogonal family is [array([-0.75592895, -0.37796447,  0.37796447, -0.37796447])]


3. E the linear space spanned by the vectors {u1,u2,u3} and P the projection matrix onto E. 
We want to compute the projector P and verify by computing the square of P that we have found a projector 
and then, compute the porjection of the vector (1,1,1,1) onto E 

In [ ]:
# here the linear space E 

u1 =np.array([-6,-3,3,-3]) 
u2 = np.array([-8,4,1,-1])
u3 = np.array([-4,-3,4,-8])
u4 = np.array([-8,-6,-7,-1]) 

#E = np.linspace(u1,u2,u3)

# we now compute the projector P 
# for that we also verify by computing the square of P 

#E = [u1,u2,u3]
E = np.column_stack((u1,u2,u3))

P = np.dot(E,np.dot(np.linalg.inv(np.dot(np.transpose(E),E)),np.transpose(E)))
print('P='+str(P)) 

# verification 

print ('the square of P =',np.dot(P,P))
# we then can see that PP = P, which is part of the definition of a projector 

# the projection of the vector (1,1,1,1) onto E 

F =np.array([[1],[1],[1],[1]])
print('F (la matrice à projeter)='+str(F)) 

proj=np.dot(P,F)
print('proj='+str(proj))



P=[[ 0.95898277 -0.04922067 -0.18457752 -0.0533224 ]
 [-0.04922067  0.94093519 -0.22149303 -0.06398687]
 [-0.18457752 -0.22149303  0.16940115 -0.23995078]
 [-0.0533224  -0.06398687 -0.23995078  0.93068089]]
the square of P = [[ 0.95898277 -0.04922067 -0.18457752 -0.0533224 ]
 [-0.04922067  0.94093519 -0.22149303 -0.06398687]
 [-0.18457752 -0.22149303  0.16940115 -0.23995078]
 [-0.0533224  -0.06398687 -0.23995078  0.93068089]]
F (la matrice à projeter)=[[1]
 [1]
 [1]
 [1]]
proj=[[ 0.67186218]
 [ 0.60623462]
 [-0.47662018]
 [ 0.57342084]]


4. What is the determinant, trace and eigenvalues of P? are those results obvious? 

In [ ]:
from numpy import linalg as LA  

print(P)

# determinant 

Det = np.linalg.det(P)
print(Det)

# the trace (summ of the diagonal element of the matrix)

trace =  np.trace(P)
print('la trace de P est', trace)

#for i in range(1,len(P)):
 # sum_diagonal = np.sum(P[i][i])
  #trace = sum_diagonal
#print(trace)

# eigenvalues of P 

w,e = LA.eig(P)

w;e
print ('the eigenvalues',w)



[[ 0.95898277 -0.04922067 -0.18457752 -0.0533224 ]
 [-0.04922067  0.94093519 -0.22149303 -0.06398687]
 [-0.18457752 -0.22149303  0.16940115 -0.23995078]
 [-0.0533224  -0.06398687 -0.23995078  0.93068089]]
-3.3299859998242246e-17
la trace de P est 3.0
the eigenvalues [8.62365241e-17 1.00000000e+00 1.00000000e+00 1.00000000e+00]


5. let R be the matrix whose rows are the vectors (u1,u2), compute the SVD of R 

In [ ]:
# the matrix R 

R = []
R.append(np.array([-6,-3,3,-3]))
R.append(np.array([-8,4,1,-1]))

print ('R=', R)

SVD = np.linalg.svd(R)
print('SVD of R = ',SVD)



R= [array([-6, -3,  3, -3]), array([-8,  4,  1, -1])]
SVD of R =  (array([[-0.62425265, -0.78122252],
       [-0.78122252,  0.62425265]]), array([10.74993038,  5.42577154]), array([[ 0.92980101, -0.11647816, -0.2468835 ,  0.2468835 ],
       [-0.05652397,  0.89216403, -0.31689777,  0.31689777],
       [ 0.25717225,  0.3086067 ,  0.9114756 ,  0.0885244 ],
       [-0.25717225, -0.3086067 ,  0.0885244 ,  0.9114756 ]]))


6. Let S=RR^T.Compute the exponential of the matrix S. Compute S -S^T 

In [ ]:
from scipy.linalg import expm, sinm, cosm


# the exponential of a matrix S 

S = np.dot(R,np.transpose(R))
print('S', S)

# we want the exponential of the matrix S 

exp =  expm(S)

print('the exponential of S is ', S)

# compute S-S^T 

ST = np.transpose(S)
C = S - ST 

print('S-ST =',C)



S [[63 42]
 [42 82]]
the exponential of S is  [[63 42]
 [42 82]]
S-ST = [[0 0]
 [0 0]]
